#!/usr/bin/env sh
#
# This is a helper script used to only invoke a subset of test environments
# associated to linting.

TOX_ENVS="pylint,ruff"

if [[ -n "$1" ]]; then
    envs=$1
else
    envs=$TOX_ENVS
fi

exec tox -e $envs
