select = [
    'ALL',
]

ignore = [
    # ignore flake8-annotations since python 2.7 is supported
    'ANN',
    # ignore various unused arguments in api definitions
    'ARG002',
    # exception chaining not supported in python 2.7
    'B904',
    # zip does not have a strict option in python 2.7
    'B905',
    # various cases in the code where catching all exceptions is desired
    'BLE',
    # we are a bit complex for now
    'C90',
    # ignore pydocstyle (interim)
    'D',
    # ignore eradicate since spdx ids and parenthesis are false flagged
    'ERA001',
    # ignore the use of string literals for exceptions
    'EM',
    # ignore samples with shebang that are not executable
    'EXE001',
    # flexible file system usage (suppress execute flag check)
    'EXE002',
    # imports are sorted lexicographically in this project
    'FBT002',
    # imports are sorted lexicographically in this project
    'I001',
    # suppress no-pep420 checks for valid support and test scripts
    'INP',
    # permit implicitly concatenated string literals over continuation line
    'ISC002',
    # multiple cases of constants and unittest-variant method styles
    'N802',
    'N806',
    # permit import aliases with case changes
    'N812',
    'N813',
    # happy with our exception naming
    'N818',
    # ignore "too many" warnings
    'PLR0911',
    'PLR0912',
    'PLR0913',
    'PLR0915',
    # project uses unittest module
    'PT',
    # pathlib not supported in python 2.7
    'PTH',
    # single quotes are preferred in this project
    'Q000',
    'Q001',
    # suppress what appears to be false-positives with these checks
    'RET504',
    'RET505',
    'RET506',
    'RET507',
    'RET508',
    # unpacking a collection literal not supported pre-python 3.5
    'RUF005',
    # use of asserts are acceptable for this tool
    'S101',
    # nested statements are sometimes preferred for code readability
    'SIM102',
    'SIM117',
    # in various places in the code, a ternary operator is not preferred
    'SIM108',
    # expected (interim) uses of private vars within the implementation
    'SLF001',
    # ignore flake8-print since we support/expect printing
    'T20',
    # purposely used long exception messages
    'TRY003',
    # ignore `raise from` suggestion since python 2.7 is supported
    'TRY200',
    # ignore desired usages of raise calls within trys
    'TRY301',
    # ignore pyupgrade since python 2.7 is supported
    'UP',
]

[per-file-ignores]
'releng_tool\api\__init__.py' = [
    'ARG002',
    'N818',
]

'releng_tool\ext\seed\__init__.py' = [
    'ARG002',
]
