#!/usr/bin/env sh
#
# This is a helper script used to only invoke a tools test run.
# Solely used for a quick way to run a supported environment
# without having to try to form one on the command line.

. scripts/tox-cifs-workdir.sh
exec tox -e tools "$@"
