[tox]
envlist =
    # linters
    ruff
    pylint
    mypy
    # unit tests
    py{310,311,312,313,314}
    pypy3

[testenv]
commands =
    {envpython} -m tests {posargs}
deps =
passenv =
    ACTIONS_RUNNER_DEBUG
    CI_DEBUG_TRACE
    RUNNER_DEBUG
setenv =
    PIP_DISABLE_PIP_VERSION_CHECK=1
    PYTHONDONTWRITEBYTECODE=1
usedevelop =
    true

# ######################################################################
# environment to verify the ability to install all extra packages
# ######################################################################

[testenv:extras]
extras =
    all

# ######################################################################
# unit testing related to specific features which require external tools
# ######################################################################

[testenv:tools]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs}
deps =
    {[testenv]deps}
    -r{toxinidir}/requirements-tools.txt
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs}
deps =
    {[testenv:tools]deps}
passenv =
    *

[testenv:tools-py-flit]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_flit}
deps =
    {[testenv]deps}
extras =
    py-flit
passenv =
    *

[testenv:tools-py-flit-old-installer]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_flit}
deps =
    {[testenv]deps}
    installer==0.5.0
extras =
    py-flit
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools-py-flit]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_flit}
deps =
    {[testenv:tools-py-flit]deps}
extras =
    {[testenv:tools-py-flit]extras}
passenv =
    *

[testenv:tools-py-hatch]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_hatch}
deps =
    {[testenv]deps}
extras =
    py-hatch
passenv =
    *

[testenv:tools-py-hatch-old-installer]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_hatch}
deps =
    {[testenv]deps}
    installer==0.5.0
extras =
    py-hatch
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools-py-hatch]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_hatch}
deps =
    {[testenv:tools-py-hatch]deps}
extras =
    {[testenv:tools-py-hatch]extras}
passenv =
    *

[testenv:tools-py-pdm]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_pdm}
deps =
    {[testenv]deps}
extras =
    py-pdm
passenv =
    *

[testenv:tools-py-pdm-old-installer]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_pdm}
deps =
    {[testenv]deps}
    installer==0.5.0
extras =
    py-pdm
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools-py-pdm]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_pdm}
deps =
    {[testenv:tools-py-pdm]deps}
extras =
    {[testenv:tools-py-pdm]extras}
passenv =
    *

[testenv:tools-py-pep517]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_pep517}
deps =
    {[testenv]deps}
extras =
    py-setuptools
passenv =
    *

[testenv:tools-py-pep517-old-installer]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_pep517}
deps =
    {[testenv:tools-py-pep517]deps}
    installer==0.5.0
extras =
    {[testenv:tools-py-pep517]extras}
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools-py-pep517]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_pep517}
deps =
    {[testenv:tools-py-pep517]deps}
extras =
    {[testenv:tools-py-pep517]extras}
passenv =
    *

[testenv:tools-py-poetry]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_poetry}
deps =
    {[testenv]deps}
extras =
    py-poetry
passenv =
    *

[testenv:tools-py-poetry-old-installer]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_poetry}
deps =
    {[testenv]deps}
    installer==0.5.0
extras =
    py-poetry
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools-py-poetry]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_poetry}
deps =
    {[testenv:tools-py-poetry]deps}
extras =
    {[testenv:tools-py-poetry]extras}
passenv =
    *

[testenv:tools-py-setuptools]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_setuptools}
deps =
    {[testenv]deps}
extras =
    py-setuptools
passenv =
    *

[testenv:tools-py-setuptools-old-installer]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_setuptools}
deps =
    {[testenv]deps}
    installer==0.5.0
extras =
    py-setuptools
passenv =
    *

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}tools-py-setuptools]
commands =
    {envpython} -m tests --test-dir tool-tests {posargs:-- python_setuptools}
deps =
    {[testenv:tools-py-setuptools]deps}
extras =
    {[testenv:tools-py-setuptools]extras}
passenv =
    *

# ######################################################################
# tests non-editable installs, to ensure interpreters package correctly
# ######################################################################

[testenv:{py310-,py311-,py312-,py313-,py314-,py315-}release]
usedevelop =
    false

# ######################################################################
# linters
# ######################################################################

[testenv:mypy]
deps =
    {[testenv]deps}
    mypy: mypy==2.1.0
setenv =
    {[testenv]setenv}
    MYPY_CACHE_DIR={toxworkdir}/.mypy_cache
commands =
    mypy \
    releng_tool

[testenv:pylint]
deps =
    {[testenv]deps}
    pylint: pylint==4.0.5
setenv =
    {[testenv]setenv}
    PYLINTHOME={toxworkdir}/.pylint_cache
commands =
    pylint \
    releng_tool \
    scripts \
    tests

[testenv:ruff]
deps =
    {[testenv]deps}
    ruff: ruff==0.15.17
setenv =
    {[testenv]setenv}
    RUFF_CACHE_DIR={toxworkdir}/.ruff_cache
commands =
    ruff \
    check \
    releng_tool \
    scripts \
    tests
