# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.12

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py312,py312-tools", "--workdir", "/tox-workdir"]
