# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.14

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py314,py314-tools", "--workdir", "/tox-workdir"]
