# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.6

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py36,py36-tools", "--workdir", "/tox-workdir"]
