# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.5

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py35,py35-tools", "--workdir", "/tox-workdir"]
