# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.10

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py310,py310-tools", "--workdir", "/tox-workdir"]
