# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.9

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py39,py39-tools", "--workdir", "/tox-workdir"]
