# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM python:3.11

COPY --chmod=744 ubuntu-deps .
RUN ./ubuntu-deps
WORKDIR "/mnt"
CMD ["tox", "-e", "py311,py311-tools", "--workdir", "/tox-workdir"]
