#!/usr/bin/env bash

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
root_dir=$(realpath "$script_dir/../../")
cfg=

if [ -n "$1" ] && [[ "$1" != -* ]]; then
    cfg="$1"
    shift
fi

if [ -z "$cfg" ]; then
    cfg="$script_dir/Dockerfile"
fi

if [ "$1" == "--build" ]; then
    exec docker build -f "$cfg" .
fi

args=(
    -v
    "$root_dir":/mnt
)
while [ "$#" -gt 0 ]; do
    [[ "$1" == "--" ]] && shift && break
    args+=("$1"); shift
done

exec docker run --rm -it "${args[@]}" "$(docker build -f "$cfg" -q .)" "$@"
