# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM debian:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update && \
    apt-get install -y pipx && \
    pipx install --global releng-tool && \
    releng-tool --version
