# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

FROM opensuse/tumbleweed:latest

RUN \
    zypper install -y sudo && \
    useradd -m default && \
    echo "default ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers

USER default
WORKDIR /home/default

RUN \
    sudo zypper install -y python3-pipx && \
    sudo pipx install --global releng-tool && \
    releng-tool --version
