#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import os


fname = os.path.join(OUTPUT_DIR, 'generated-licenses.json')
with open(fname, 'w') as f:
    json.dump(RELENG_GENERATED_LICENSES, f)
