#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import os

target = releng_join(TARGET_DIR, 'metadata-a')
releng_copy('metadata', target)

fname = os.path.join(TARGET_DIR, 'invoke-env-a.json')
with open(fname, 'w') as f:
    json.dump(dict(os.environ), f)
