# SPDX-License-Identifier: BSD-2-Clause
# Copyright releng-tool

from collections import OrderedDict
from copy import deepcopy
from datetime import datetime
from datetime import timezone
from releng_tool import __version__ as releng_version
from releng_tool.defs import PackageInstallType
from releng_tool.defs import SbomFormatType
from releng_tool.defs import VcsType
from releng_tool.engine.sbom.csv import generate_csv
from releng_tool.engine.sbom.html import generate_html
from releng_tool.engine.sbom.json import generate_json
from releng_tool.engine.sbom.json_spdx import generate_json_spdx
from releng_tool.engine.sbom.text import generate_text
from releng_tool.tool.git import GIT
from releng_tool.tool.hg import HG
from releng_tool.util.hash import BadFileHashLoadError
from releng_tool.util.hash import BadFormatHashLoadError
from releng_tool.util.hash import load as load_hashes
from releng_tool.util.io_mkdir import mkdir
from releng_tool.util.log import err
from releng_tool.util.log import verbose
from releng_tool.util.log import warn
from releng_tool.util.spdx import ConjunctiveLicenses
from releng_tool.util.spdx import LicenseEntries
from releng_tool.util.spdx import spdx_parse
import hashlib
import os
import uuid
import xml.dom.minidom as xml_minidom
import xml.etree.ElementTree as ET


# version string of the SBOM definition generated by releng-tool
SBOM_VERSION = '1'

# spdx license list version used
SPDX_LLVERSION = '3.28'

# specification followed for generated spdx-sboms
SPDX_SPEC = 'SPDX-2.3'


class SbomManager:
    """
    sbom manager

    An SBOM manager is used to help generate a software build-of-materials for
    a releng-tool project. This can be used to help track package versions
    used, dependency history and more.

    Args:
        opts: options used to configure the engine

    Attributes:
        generated: list of generated sbom files
        opts: options used to configure the engine
    """
    def __init__(self, opts):
        self.generated = []
        self.opts = opts

    def build_cache(self, pkgs):
        """
        compile a cache of sbom information

        This request will compile SBOM information for the running releng-tool
        project. Provides packages will be cycled through to track package
        versions and licenses. The result should be a dictionary of
        information which can then be used for generating an SBOM output file.

        Args:
            pkgs: packages which may be assigned licenses

        Returns:
            the sbom cache
        """

        cache = OrderedDict()
        cache['type'] = 'releng-tool-sbom'
        cache['report-id'] = str(uuid.uuid4())
        cache['packages'] = OrderedDict()
        cache['host-packages'] = OrderedDict()
        cache['releng-tool-sbom-version'] = SBOM_VERSION
        cache['releng-tool-version'] = releng_version

        for pkg in pkgs:
            # ignore placeholder packages
            if pkg.vcs_type == VcsType.NONE:
                continue

            # determine location where to store package cache
            if pkg.install_type == PackageInstallType.HOST:
                cache_base = cache['host-packages']
            else:
                cache_base = cache['packages']

            cache_pkg = cache_base.setdefault(pkg.name, OrderedDict())

            # generate a unique id to identify this package across different
            # builds and other releng-tool projects -- just a simple id string
            # to help reference a package component when interpreters do not
            # want to explicitly rely on a package name
            uid_str = 'releng-tool-' + pkg.name
            uid_data = uid_str.encode('utf_8')
            uid = hashlib.sha1(uid_data).hexdigest()  # noqa: S324

            # build a representation of a version (fallback on revision if no
            # version value is set)
            version_desc = pkg.version
            if not version_desc and pkg.revision:
                version_desc = pkg.revision

            # try to resolve a "best" revision representation of the sources
            # being used; for special vcs types, try to pull the revision,
            # otherwise use the explicit revision configured; if all this
            # resolves to a value that matches the version, we ignore this
            # description
            revision_desc = pkg.revision

            if pkg.vcs_type == VcsType.GIT:
                rv, detected_revision = GIT.execute_rv(
                    f'--git-dir={pkg.cache_dir}',
                    'rev-parse',
                    f'{pkg.revision}^{{commit}}',
                )
                if rv == 0:
                    revision_desc = detected_revision
            elif pkg.vcs_type == VcsType.HG:
                rv, detected_revision = HG.execute_rv(
                    '--repository',
                    pkg.cache_dir,
                    'log',
                    '--rev',
                    pkg.revision,
                    '--template',
                    '{node}',
                )
                if rv == 0:
                    revision_desc = detected_revision

            if revision_desc == version_desc:
                revision_desc = None

            # populate package cache
            cache_pkg['hashes'] = []
            cache_pkg['id'] = uid
            cache_pkg['licenses'] = []
            cache_pkg['revision'] = revision_desc
            cache_pkg['site'] = pkg.site or ''
            cache_pkg['version'] = version_desc

            # extract hash entries (if any)
            try:
                hash_info = load_hashes(pkg.hash_file)
                if hash_info:
                    for type_, hash_, asset in hash_info:
                        cache_pkg['hashes'].append({
                            'algorithm': type_,
                            'file': asset,
                            'hash': hash_,
                        })
            except (BadFileHashLoadError, BadFormatHashLoadError):
                pass

            # copy license entries (if any)
            if pkg.license:
                cache_pkg['licenses'] = deepcopy(pkg.license)

        # remove host packages entry if we have no host packages
        if not cache['host-packages']:
            del cache['host-packages']

        # if no project identifier is set, generate one
        if 'releng-tool-pid' not in cache:
            pid_tmp = 'releng-tool'
            for pkg in pkgs:
                pid_tmp += ';' + pkg.name
            uid_data = pid_tmp.encode('utf_8')
            pid = hashlib.sha1(uid_data).hexdigest()  # noqa: S324
            cache['releng-tool-pid'] = 'releng-tool-' + pid[:8]

        # after processing all packages, now is a good time to timestamp the
        # cache of when this content was populated
        utc_now = datetime.now(tz=timezone.utc)
        utc_now_str = utc_now.strftime("%Y-%m-%dT%H:%M:%S") + 'Z'
        cache['datetime'] = utc_now_str

        return cache

    def generate(self, cache):
        """
        generate an sbom file for the project

        Compiles a software build-of-materials document based on the cache
        information populated from a releng-tool project.

        Args:
            cache: the sbom cache

        Returns:
            ``True`` if the file was generated; ``False`` if the file could
            not be generated
        """

        # ensure output directory exists before any attempts to generate
        # (e.g. if an engine was just asked to create SBOMs)
        if not mkdir(self.opts.out_dir):
            return False

        fmt = self.opts.sbom_format
        all_fmt = SbomFormatType.ALL in fmt

        sbom_csv = all_fmt or SbomFormatType.CSV in fmt
        sbom_html = all_fmt or SbomFormatType.HTML in fmt
        sbom_json = all_fmt or SbomFormatType.JSON in fmt
        sbom_json_spdx = all_fmt or SbomFormatType.JSON_SPDX in fmt
        sbom_rdf_spdx = all_fmt or SbomFormatType.RDF_SPDX in fmt \
             or SbomFormatType.RDP_SPDX in fmt
        sbom_text = all_fmt or SbomFormatType.TEXT in fmt
        sbom_xml = all_fmt or SbomFormatType.XML in fmt

        if SbomFormatType.RDP_SPDX in fmt:
            warn(f'detected obsolete sbom format "{SbomFormatType.RDP_SPDX}"; '
                 f'switch to "{SbomFormatType.RDF_SPDX}"')

        # if not formats are configured, enable text-SBOM by default
        if not fmt:
            sbom_text = True

        try:
            if sbom_csv:
                generate_csv(self, cache)

            if sbom_html:
                generate_html(self, cache)

            if sbom_json:
                generate_json(self, cache)

            if sbom_json_spdx:
                generate_json_spdx(self, cache)

            if sbom_rdf_spdx:
                self._generate_rdf_spdx(cache)

            if sbom_text:
                generate_text(self, cache)

            if sbom_xml:
                self._generate_xml(cache)
        except OSError as e:
            err('unable to generate sbom output\n'
                '    {}\n', e)
            return False

        return True

    def _generate_rdf_spdx(self, cache):
        """
        generate a SPDX compliant RDF (XML) format sbom file

        Compiles an RDF-formatted software build-of-materials document based
        on the cache information populated from a releng-tool project.

        Args:
            cache: the sbom cache
        """

        rdf_license_burl = 'http://spdx.org/licenses/'
        rdf_term_na = 'http://spdx.org/rdf/terms#noassertion'
        rdf_term_none = 'http://spdx.org/rdf/terms#none'
        rdf_term_rdesc = 'http://spdx.org/rdf/terms#relationshipType_describes'

        data_license_ref = 'http://spdx.org/licenses/CC0-1.0'
        prj_name = cache['releng-tool-pid']
        tool_ref = 'Tool: releng-tool-' + cache['releng-tool-version']
        uid = cache['report-id']
        base_namespace = f'https://spdx.org/spdxdocs/{prj_name}-{uid}'
        doc_namespace = f'{base_namespace}#SPDXRef-DOCUMENT'

        # resource description root
        rdf_root = ET.Element('rdf:RDF')
        rdf_root.set('xmlns:rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#')
        rdf_root.set('xmlns:spdx', 'http://spdx.org/rdf/terms#')
        rdf_root.set('xmlns:rdfs', 'http://www.w3.org/2000/01/rdf-schema#')

        # spdx document root
        root = ET.SubElement(rdf_root, 'spdx:SpdxDocument')
        root.set('rdf:about', doc_namespace)

        # common elements
        XML_ELEMENT(root, 'spdx:specVersion', SPDX_SPEC)
        XML_ELEMENT(root, 'spdx:name', prj_name)
        dle = ET.SubElement(root, 'spdx:dataLicense')
        dle.set('rdf:resource', data_license_ref)
        creation_info_container = ET.SubElement(root, 'spdx:creationInfo')

        cinfo_root = ET.SubElement(creation_info_container, 'spdx:CreationInfo')
        XML_ELEMENT(cinfo_root, 'spdx:created', cache['datetime'])
        XML_ELEMENT(cinfo_root, 'spdx:creator', tool_ref)
        XML_ELEMENT(cinfo_root, 'spdx:licenseListVersion', SPDX_LLVERSION)

        # package entries
        package_entries = [
            'packages',
            'host-packages',
        ]

        for entry in package_entries:
            data = cache.get(entry, None)
            if not data:
                continue

            for pkg_name, pkg in data.items():
                pkg_rev = pkg.get('revision', '')

                pkg_dl_loc = pkg.get('site', 'NONE')
                if pkg_dl_loc == 'local':
                    pkg_dl_loc = 'NONE'

                rcontainer = ET.SubElement(root, 'spdx:relationship')
                rroot = ET.SubElement(rcontainer, 'spdx:Relationship')
                rtype = ET.SubElement(rroot, 'spdx:relationshipType')
                rtype.set('rdf:resource', rdf_term_rdesc)
                relement = ET.SubElement(rroot, 'spdx:relatedSpdxElement')
                proot = ET.SubElement(relement, 'spdx:Package')

                pkg_namespace = f'{base_namespace}#SPDXRef-{pkg_name}'
                proot.set('rdf:about', pkg_namespace)

                XML_ELEMENT(proot, 'spdx:specVersion', SPDX_SPEC)
                XML_ELEMENT(proot, 'spdx:name', pkg_name)
                XML_ELEMENT(proot, 'spdx:versionInfo', pkg.get('version', ''))
                XML_ELEMENT(proot, 'spdx:downloadLocation', pkg_dl_loc)
                if pkg_rev:
                    XML_ELEMENT(proot, 'spdx:sourceInfo', f'commit {pkg_rev}')
                XML_ELEMENT(proot, 'spdx:filesAnalyzed', 'false')

                license_droot = ET.SubElement(proot, 'spdx:licenseDeclared')
                license_croot = ET.SubElement(proot, 'spdx:licenseConcluded')
                license_croot.set('rdf:resource', rdf_term_na)

                # if we have a parsed SPDX license string, either assign the
                # resource to the single license or prepare a list of license
                # entries; if not parsable, claim no assertion; and no license
                # information as none
                pkg_licenses = spdx_parse(pkg['licenses'])
                if pkg_licenses:
                    def process_nested_licenses(base, licenses):
                        if isinstance(licenses, ConjunctiveLicenses):
                            root_entry_type = 'spdx:ConjunctiveLicenseSet'
                        else:
                            root_entry_type = 'spdx:DisjunctiveLicenseSet'

                        root_entry = ET.SubElement(base, root_entry_type)
                        for license_entry in licenses:
                            res = ET.SubElement(root_entry, 'spdx:member')

                            if isinstance(license_entry, LicenseEntries):
                                process_nested_licenses(res, license_entry)
                            else:
                                process_license_withex(res, license_entry)

                    def process_license_withex(root, license_entry):
                        license_parts = license_entry.split(' WITH ')

                        if len(license_parts) > 1:
                            sroot = ET.SubElement(root,
                                'spdx:WithExceptionOperator')

                            res = ET.SubElement(sroot, 'spdx:member')
                            process_license_orlater(res, license_parts[0])

                            res = ET.SubElement(sroot, 'spdx:licenseException')
                            exception = license_parts[1]
                            evalue = rdf_license_burl + exception + '.html'
                            res.set('rdf:resource', evalue)
                        else:
                            process_license_orlater(root, license_parts[0])

                    def process_license_orlater(root, license_entry):
                        resource = rdf_license_burl + license_entry.strip('+')

                        if license_entry.endswith('+'):
                            sroot = ET.SubElement(root, 'spdx:OrLaterOperator')
                            res = ET.SubElement(sroot, 'spdx:member')
                            res.set('rdf:resource', resource)
                        else:
                            root.set('rdf:resource', resource)

                    if isinstance(pkg_licenses, LicenseEntries):
                        process_nested_licenses(license_droot, pkg_licenses)
                    else:
                        process_license_withex(license_droot, pkg_licenses)

                elif pkg['licenses']:
                    license_droot.set('rdf:resource', rdf_term_na)
                else:
                    license_croot.set('rdf:resource', rdf_term_none)
                    license_droot.set('rdf:resource', rdf_term_none)

        # writing the processed cache data to a file
        verbose('writing sbom (rdf-spdx)')
        sbom_file = os.path.join(self.opts.out_dir, 'sbom-spdx.xml')
        xml = ET.tostring(rdf_root, 'utf_8')
        tree = xml_minidom.parseString(xml)

        with open(sbom_file, 'w') as f:
            rdf_tree = tree.childNodes[0]
            data = rdf_tree.toprettyxml(indent=' ' * 4)
            f.write(data)

        self.generated.append(sbom_file)

    def _generate_xml(self, cache):
        """
        generate an XML format sbom file

        Compiles an XML-formatted software build-of-materials document based
        on the cache information populated from a releng-tool project.

        Args:
            cache: the sbom cache
        """

        root = ET.Element(cache['type'])
        root.set('version', cache['releng-tool-sbom-version'])

        # common root entries
        ET.SubElement(root, 'report-id').text = cache['report-id']
        ET.SubElement(root, 'generated').text = cache['datetime']

        # package entries
        package_entries = [
            'packages',
            'host-packages',
        ]

        for entry in package_entries:
            data = cache.get(entry, None)
            if not data:
                continue

            packages_root = ET.SubElement(root, entry)

            for pkg_name, pkg in data.items():
                pkg_root = ET.SubElement(packages_root, 'package')
                pkg_root.set('id', pkg['id'])
                ET.SubElement(pkg_root, 'name').text = pkg_name
                ET.SubElement(pkg_root, 'version').text = pkg.get('version', '')
                ET.SubElement(pkg_root, 'site').text = pkg.get('site', '')

                revision = pkg.get('revision', '')
                if revision:
                    ET.SubElement(pkg_root, 'revision').text = revision

                licenses_root = ET.SubElement(pkg_root, 'licenses')
                for pkg_license in pkg['licenses']:
                    ET.SubElement(licenses_root, 'license').text = pkg_license

                hashes_root = ET.SubElement(pkg_root, 'hashes')
                for ph in pkg['hashes']:
                    hr = ET.SubElement(hashes_root, 'hash')
                    ET.SubElement(hr, 'algorithm').text = ph['algorithm']
                    ET.SubElement(hr, 'file').text = ph['file']
                    ET.SubElement(hr, 'hash').text = ph['hash']

        # extra information
        rtv = ET.SubElement(root, 'releng-tool-version')
        rtv.text = cache['releng-tool-version']

        # writing the processed cache data to a file
        verbose('writing sbom (xml)')
        sbom_file = os.path.join(self.opts.out_dir, 'sbom.xml')
        xml = ET.tostring(root, 'utf_8')
        tree = xml_minidom.parseString(xml)

        with open(sbom_file, 'w') as f:
            data = tree.toprettyxml(indent=' ' * 4)
            f.write(data)

        self.generated.append(sbom_file)


def XML_ELEMENT(root, name, text=None):
    """
    helper to build an xml element

    Args:
        root: the root element to create on
        name: the name of the new element
        text (optional): the text to apply to the new element

    Returns:
        the newly created element
    """

    element = ET.SubElement(root, name)

    if text:
        element.text = text

    return element
