name: doc-update

on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/doc-update.yml'
      - 'Documentation/**'
      - 'CHANGES.rst'

jobs:
  development-doc-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout releng-tool
      uses: actions/checkout@v2
      with:
        path: releng-tool

    - name: Checkout releng-tool-doc-translations
      uses: actions/checkout@v2
      with:
        repository: releng-tool/releng-tool-doc-translations
        path: releng-tool-doc-translations

    - name: Checkout releng-tool-doc-translations-builder
      uses: actions/checkout@v2
      with:
        repository: releng-tool/releng-tool-doc-translations-builder
        path: releng-tool-doc-translations-builder

    - name: Checkout releng-tool-www-docs
      uses: actions/checkout@v2
      with:
        repository: releng-tool/releng-tool-www-docs
        path: releng-tool-www-docs
        ssh-key: ${{ secrets.WWW_DOCS_AUTOPUBLISH }}

    - name: Install dependencies
      run: |
        sudo apt-get install gettext 
        pip install --upgrade \
            "docutils<0.17" \
            sphinx \
            sphinx-intl \
            sphinx-rtd-theme

    - name: Update development translations
      run: |
        cd releng-tool-doc-translations
        ./update \
            --version development \
            --version-dir $GITHUB_WORKSPACE/releng-tool

    - name: Build development translations
      run: |
        cd releng-tool-doc-translations-builder
        ./build \
            --locale $GITHUB_WORKSPACE/releng-tool-doc-translations \
            --version development \
            --version-dir $GITHUB_WORKSPACE/releng-tool

    - name: Moving over new development translations
      run: |
        find $GITHUB_WORKSPACE/releng-tool-www-docs/ \
            -type d -wholename "*/development" -exec rm -r {} +
        rsync -av \
            $GITHUB_WORKSPACE/releng-tool-doc-translations-builder/_build/ \
            $GITHUB_WORKSPACE/releng-tool-www-docs/

    - name: Publish development changes
      run: |
        cd releng-tool-www-docs
        git config --global user.name 'releng-tool bot'
        git config --global user.email 'noreply@releng.io'
        git add .
        if git commit -am "automated development update"; then
          git push origin master
        fi
